MySinglesWard/Models/OrganizationType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MSW.Models
{
    public enum OrganizationType{ BISHOPRIC, ELDERS_QUORUM, RELIEF_SOCIETY }
}

MySinglesWard/Models/Reports/OrganizationReport.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MSW.Models.dbo;
using MSW.Utilities;

namespace MSW.Models.Reports
{
    public class OrganizationReport
    {
        public Organization org { get; set; }
        public List<TeachingMonth> months { get; set; }

        //Dictionary<MonthID, Double>
        public Dictionary<int, int> teachingPercentages { get; set; }

        public int callingsFilled { get; set; }
        public int callingsEmpty { get; set; }

        public OrganizationReport(int orgID)
        {
            this.org = Organization.get(orgID);

            //get the teaching Line Graph info
            months = Cache.GetList(Repository.getInstance().getTeachingMonths(3), x => Cache.getCacheKey<TeachingMonth>(x),
                y => TeachingMonth.get(y));

            teachingPercentages = new Dictionary<int, int>();

            foreach (var month in months)
            {
                teachingPercentages.Add(month.TeachingMonthID, 
                    (int)Repository.getInstance().getTeachingPercentage(orgID, month.TeachingMonthID));
            }

            //get the calling info
            List<Calling> callings = Cache.GetList(Repository.getInstance().CallingIDs(orgID), x => Cache.getCacheKey<Calling>(x),
                y => Calling.get(y));

            callingsFilled = callings.Where(x => x.MemberID != 0).Count();
            callingsEmpty = callings.Count - callingsFilled;

        }


    }
}

MySinglesWard/Models/dao/Companionship.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MSW.Utilities;
using MSW.Model;

namespace MSW.Models.dbo
{
    [Serializable]
    public class Companionship
    {
        public int CompanionshipID { get; set; }
        public int DistrictID { get; set; }

		public static Companionship get(int CompanionshipID)
		{
			Companionship comp = Cache.Get(Cache.getCacheKey<Companionship>(CompanionshipID)) as Companionship;

			if (comp == null)
			{
				comp = new Companionship(CompanionshipID);
				Cache.Set(Cache.getCacheKey<Companionship>(CompanionshipID), comp);
			}

			return comp;
		}

		public static void save(Companionship comp)
		{
			Cache.Remove(Cache.getCacheKey<Companionship>(comp.CompanionshipID));

            _NukeCache(comp);

			using (var db = new DBmsw())
			{
				var targetComp = db.tCompanionships.SingleOrDefault(x => x.CompanionshipID == comp.CompanionshipID);
                
                targetComp.CompanionshipID = comp.CompanionshipID;
				targetComp.DistrictID = comp.DistrictID;                

				db.SubmitChanges();

				Cache.Set(Cache.getCacheKey<Companionship>(comp.CompanionshipID), comp);
			}
		}

        public static Companionship create(tCompanionship comp)
        {
            using (var db = new DBmsw())
            {
                db.tCompanionships.InsertOnSubmit(comp);

                db.SubmitChanges();

                Companionship newComp = new Companionship(comp.CompanionshipID);
                Cache.Set(Cache.getCacheKey<Companionship>(newComp.CompanionshipID), newComp);

                _NukeCache(newComp);

                return newComp;
            }
        }

		public static void remove(Companionship comp)
		{
			Cache.Remove(Cache.getCacheKey<Companionship>(comp.CompanionshipID));

            _NukeCache(comp);

			using (var db = new DBmsw())
			{
				db.tCompanionships.DeleteOnSubmit(db.tCompanionships.SingleOrDefault(x => x.CompanionshipID == comp.CompanionshipID));
				db.SubmitChanges();
			}
		}

        private Companionship(int CompanionshipID)
		{
			using (var db = new DBmsw())
			{
				var comp = db.tCompanionships.SingleOrDefault(x => x.CompanionshipID == CompanionshipID);

				this.CompanionshipID = comp.CompanionshipID;
				DistrictID = comp.DistrictID;
			}
		}

        private static void _NukeCache(Companionship comp)
        {
            Repository r = Repository.getInstance();

            r.removeCompanionships(comp.DistrictID);
        }
    }
}

MySinglesWard/Models/dao/Organization.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MSW.Utilities;

namespace MSW.Models.dbo
{
	[Serializable]
	public class Organization
	{
		public int OrgID { get; set; }
		public double WardID { get; set; }
		public int? LeaderCallingID { get; set; }
		public string Title { get; set; }
		public string ReportID { get; set; }
		public int SortID { get; set; }

		public static Organization get(int OrgID)
		{
			Organization org = Cache.Get(Cache.getCacheKey<Organization>(OrgID)) as Organization;

			if (org == null)
			{
				org = new Organization(OrgID);
				Cache.Set(Cache.getCacheKey<Organization>(OrgID), org);
			}

			return org;
		}

		public static void save(Organization org)
		{
			Cache.Remove(Cache.getCacheKey<Organization>(org.OrgID));

			Repository r = Repository.getInstance();
            r.NukeReportKeys(org);

			using (var db = new DBmsw())
			{
				var targetOrg = db.tOrganizations.SingleOrDefault(x => x.OrgID == org.OrgID);

				targetOrg.WardID = org.WardID;
				targetOrg.LeaderCallingID = org.LeaderCallingID;
				targetOrg.Title = org.Title;
				targetOrg.ReportID = org.ReportID;
				targetOrg.SortID = org.SortID;

				db.SubmitChanges();

				Cache.Set(Cache.getCacheKey<Organization>(org.OrgID), org);
			}
		}

		public static void remove(Organization org)
		{
			Cache.Remove(Cache.getCacheKey<Organization>(org.OrgID));
			Cache.Remove("Organizations:" + org.WardID);

			Repository r = Repository.getInstance();
            r.NukeReportKeys(org);

			using (var db = new DBmsw())
			{
				db.tOrganizations.DeleteOnSubmit(db.tOrganizations.SingleOrDefault(x => x.OrgID == org.OrgID));
				db.SubmitChanges();
			}
		}

		private Organization(int OrgID)
		{
			using (var db = new DBmsw())
			{
				var org = db.tOrganizations.SingleOrDefault(x => x.OrgID == OrgID);

				this.OrgID = org.OrgID;
				Title = org.Title;
				LeaderCallingID = org.LeaderCallingID;
				ReportID = org.ReportID;
				SortID = org.SortID;
				WardID = org.WardID;
			}
		}

	}
}

MySinglesWard/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MSW.Models;
using MSW.Utilities;
using MSW.Model;
using MSW.Models.dbo;
using MSW.Exceptions;
using System.Collections.Specialized;
using System.Text;
using System.IO;
using System.Web.UI.WebControls;
using MSW.Models.Reports;
using MSW.Models.dao;

namespace MSW.Controllers
{
	[HandleError]
	public class OrganizationController : Controller
	{
		private const int NOTINORG = 0;
		//
		// GET: /Organization/
		[Authorize]
		public ActionResult Index()
		{
			try
			{
				if (Session["Username"] == null)
					_NewSession();

				int orgID = _getUserOrganizationID();
				MSWOrganizationModel model = MSWOrganizationModel.get(orgID);

				return View(model);
			}
			catch (OrganizationNotSetException e)
			{
				//Bishopric user needs to go select an organization before they can continue
				return RedirectToAction("SelectOrganization");
			}
			catch (UserNotInOrganizationException e)
			{
				//User not in an organization yet
				return RedirectToAction("RequestOrganization");
			}
		}

		#region Membership

		//
		// GET: /Organization/Membership
		[Authorize]
		public ActionResult Membership()
		{
			try
			{
				int orgID = _getUserOrganizationID();

				if (Session["Username"] == null)
					_NewSession();

				MSWOrganizationModel model = MSWOrganizationModel.get(orgID);

				//Get list of members
				List<MemberModel> members = Cache.GetList(model.orgMembers.Select(x => x.MemberID).ToList(),
					x => Cache.getCacheKey<MemberModel>(x), y => MemberModel.get(y));

				members = members.OrderBy(x => x.memberSurvey.prefName).ThenBy(x => x.user.LastName).ToList();

				//Set header variable
				ViewBag.Header = model.org.Title;
				ViewBag.orgID = model.org.OrgID;
				ViewBag.ReportID = model.org.ReportID;

				//Create Sort options
				SelectListItem[] printList = new SelectListItem[3];
				printList[0] = new SelectListItem { Text = "By Last Name", Value = "lastName" };
				printList[2] = new SelectListItem { Text = "By Apartment", Value = "apartment" };
				printList[1] = new SelectListItem { Text = "By First Name & M/F", Value = "name" };
				ViewData["DropDown"] = printList;

				return View(members);
			}
			catch (OrganizationNotSetException e)
			{
				//Bishopric user needs to go select an organization before they can continue
				return RedirectToAction("SelectOrganization");
			}
			catch (UserNotInOrganizationException e)
			{
				//User not in an organization yet
				return RedirectToAction("RequestOrganization");
			}
		}

		//
		// GET: /Organization/ManageMembership
		[Authorize(Roles = "Bishopric, Elders Quorum, Relief Society")]
		public ActionResult ManageMembership()
		{
			try
			{
				if (Session["Username"] == null)
					_NewSession();

				int orgID = _getUserOrganizationID();
				MSWOrganizationModel model = MSWOrganizationModel.get(orgID);
				model.generateMembershipLists();

				return View(model);
			}
			catch (OrganizationNotSetException e)
			{
				//Bishopric user needs to go select an organization before they can continue
				return RedirectToAction("SelectOrganization");
			}
			catch (UserNotInOrganizationException e)
			{
				//User not in an organization yet
				return RedirectToAction("RequestOrganization");
			}
		}

		//
		// GET: /Organization/ManageMembership
		[Authorize(Roles = "Bishopric, Elders Quorum, Relief Society")]
		[HttpPost]
		public bool ManageMembership(int? id)
		{
			try
			{
				int orgID = _getUserOrganizationID();
				_checkUserWard(orgID);

				NameValueCollection form = HttpUtility.ParseQueryString(Request.Form["MemberIDList"]);

				foreach (string MemberID in form.AllKeys)
				{
					string addToOrg = form.Get(MemberID);
					if (addToOrg != "false")
						_AddMemberToOrganization(MemberID, orgID);
				}
			}
			catch (OrganizationNotSetException e)
			{
				//Bishopric user needs to go select an organization before they can continue
				throw e;
			}
			catch (UserNotInOrganizationException e)
			{
				//User not in an organization yet
				throw e;
			}
			return true;
		}

		//Adds a member to an organization
		private void _AddMemberToOrganization(string id, int orgID)
		{
			int MemberID = int.Parse(id);

			MSWUser member = MSWUser.getUser(MemberID);
			Organization org = Organization.get(orgID);

			if (member.WardStakeID != org.WardID)
				throw new UserNotInOrganizationException();

			OrganizationMember orgMember = OrganizationMember.get(MemberID);

			if (orgMember == null)
			{
				tOrganizationMember newMember = new tOrganizationMember();
				newMember.MemberID = MemberID;
				newMember.OrgID = orgID;
				OrganizationMember.create(newMember);
			}
			else
			{
				orgMember.OrgID = orgID;
				orgMember.PendingOrgID = null;
				orgMember.status = (int)OrganizationMember.Status.APPROVED;
				OrganizationMember.save(orgMember);
			}
		}

		[Authorize(Roles = "Bishopric, Elders Quorum, Relief Society")]
		public bool ApproveNewMembership(string button, int MemberID)
		{
			OrganizationMember orgMember = OrganizationMember.get(MemberID);

			try
			{
				_checkUserWard((int)orgMember.PendingOrgID);

				// Member Approved
				if (button.Equals("approve"))
				{
					orgMember.status = (int)OrganizationMember.Status.APPROVED;
					orgMember.OrgID = (int)orgMember.PendingOrgID;
				}
				else // Not Approved
				{
					orgMember.status = orgMember.OrgID != NOTINORG ?
											(int)OrganizationMember.Status.APPROVED : (int)OrganizationMember.Status.NONE;
					orgMember.PendingOrgID = null;
				}

				OrganizationMember.save(orgMember);
			}
			catch
			{
				throw new Exception();
			}

			//Remove the organization membership from cache
			Repository r = Repository.getInstance();
			r.removeOrganizationMembership(orgMember.OrgID);

			return true;
		}

		//Removes a member from an organization
		[Authorize(Roles = "Bishopric, Elders Quorum, Relief Society")]
		public bool RemoveMember(int id)
		{
			OrganizationMember orgMember = OrganizationMember.get(id);
			_checkUserWard(orgMember.OrgID);

			//Remove member from current teaching assignment in the organization
			MSWtools.removeMemberFromTeachingAssignment(orgMember.MemberID);

			//Remove the Member from the organization
			OrganizationMember.remove(orgMember);

			return true;
		}

		//Gets the organization member names for the member search feature on the Organization List
		[Authorize]
		public bool getMemberNames(string name_startsWith, int orgID)
		{
			//OrganizationMember orgMember = OrganizationMember.getByMemberID();


			return true;
		}

		//
		// GET: /Organization/SelectOrganization
		[Authorize(Roles = "Bishopric")]
		public ActionResult SelectOrganization()
		{
			if (Session["Username"] == null)
				_NewSession();

			//Get member information
			MemberModel member = MemberModel.get(User.Identity.Name);

			//Get all the elders quorums and relief societies in the ward to select which org they want to manage
			Repository r = Repository.getInstance();
			List<Organization> orgs = Cache.GetList(r.OrganizationIDs(member.user.WardStakeID), x => Cache.getCacheKey<Organization>(x), y => Organization.get(y));

			//Filter out orgs based on authentication type
			if (User.IsInRole("Bishopric"))
				orgs = orgs.Where(x => x.ReportID == "Relief Society" || x.ReportID == "Elders Quorum").ToList();
			else if (User.IsInRole("EldersQuorum"))
				orgs = orgs.Where(x => x.ReportID == "Elders Quorum").ToList();
			else if (User.IsInRole("ReliefSociety"))
				orgs = orgs.Where(x => x.ReportID == "Relief Society").ToList();

			List<MSWOrganizationModel> orgModels = new List<MSWOrganizationModel>();

			foreach (Organization org in orgs)
				orgModels.Add(MSWOrganizationModel.get(org.OrgID));

			orgModels = orgModels.OrderBy(x => x.org.ReportID).ThenBy(x => x.org.Title).ToList();
			return View(orgModels);
		}

		//Used to select which organization will be managed. This is set in a session variable
		[Authorize(Roles = "Bishopric")]
		[HttpPost]
		public ActionResult SelectOrganization(int orgID)
		{
			//Get user and make sure the organization is in the ward of the user
			MSWUser user = MSWUser.getUser(User.Identity.Name);
			Organization org = Organization.get(orgID);

			try
			{

				if (user.WardStakeID != org.WardID)
					return RedirectToAction("Error");

				//Assign the selected org to the user
				Session["orgID"] = orgID.ToString();
				return RedirectToAction("Index");
			}
			catch (NullReferenceException e)
			{
				return RedirectToAction("Error");
			}
		}

		//
		// GET: /Organization/RequestOrganization
		[Authorize]
		public ActionResult RequestOrganization()
		{
			if (Session["Username"] == null)
				_NewSession();

			//Get member information
			MemberModel member = MemberModel.get(User.Identity.Name);

			//Check if member has made a request
			OrganizationMember orgMember = OrganizationMember.get(member.user.MemberID);
			if (orgMember != null)
				if (orgMember.status == (int)OrganizationMember.Status.PENDING)
					return RedirectToAction("OrganizationPending");

			//Get all the elders quorums and relief societies in the ward to select which org they want to manage
			Repository r = Repository.getInstance();
			List<Organization> orgs = Cache.GetList(r.OrganizationIDs(member.user.WardStakeID), x => Cache.getCacheKey<Organization>(x), y => Organization.get(y));

			//Filter out orgs based on authentication type
			if (member.memberSurvey.gender)
				orgs = orgs.Where(x => x.ReportID == "Elders Quorum").ToList();
			else
				orgs = orgs.Where(x => x.ReportID == "Relief Society").ToList();

			List<MSWOrganizationModel> orgModels = new List<MSWOrganizationModel>();

			foreach (Organization org in orgs)
				orgModels.Add(MSWOrganizationModel.get(org.OrgID));

			orgModels = orgModels.OrderBy(x => x.org.Title).ThenBy(x => x.org.Title).ToList();
			return View(orgModels);
		}

MySinglesWard/Views/Organization/Index.cshtml
@model MSW.Models.MSWOrganizationModel
@{
    Page.Title = Model.org.Title;
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
    Page.Header = Model.org.Title;
}
@section HeadContent
{
    <script src="../../Scripts/js/jquery-ui-1.8.13.custom.min.js" type="text/javascript"></script>
}
<table style="margin-left: 20px">
    <tr valign="top">
        <td>
            <table class="ProfileText">
                <tr>
                    <td>
                        @if (Model.org.ReportID == "Elders Quorum")
                        {
                            <img src="/Content/images/EQlogo.png" alt="@Model.org.Title" />
                        }
                        else
                        {
                            <img src="/Content/images/RSlogo.png" alt="@Model.org.Title" />
                        }
                    </td>
                    <td>
                        <table style="width: 540px; margin: 17px">
                            <tr>
                                <td>
                                    President:
                                </td>
                                <td>
                                    @if (Model.president != null)
                                    { 
                                        @(Model.president.user.LastName + ", " + Model.president.memberSurvey.prefName)
                                    }
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    # of members:
                                </td>
                                <td>
                                    @Model.orgMembers.Count
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @(Model.org.ReportID == "Elders Quorum" ? "Quorum's Home Teaching Percentage:" : "Relief Society's Teaching Percentage:")
                                </td>
                                <td>
                                    @((int)Model.currentTeachingPercentage)%
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
            <div style="clear: both;">
                &nbsp;</div>
            <!-- end #content -->
            @if (User.IsInRole("Elders Quorum") || User.IsInRole("Relief Society") || User.IsInRole("Bishopric"))
            {  
                <div id="tabs">
                    <ul>
                        <li><a href="#Membership">Membership Approval</a></li>
                    </ul>
                    <div id="Membership">
                        @if (Model.MemberApprovals.Count == 0)
                        { 
                            <p>
                                There are no memberships to approve.</p>
                        }
                        else
                        { 
                            <p>
                                These members were just added to your organization and are waiting approval:</p>
                            <br />
                            <table class="ApprovalList">
                                @foreach (var item in Model.MemberApprovals)
                                { 
                                    <tr id="@item.user.MemberID">
                                        <td>
                                            <img class="smallPic" src="/Photo/@item.photo.FileName" alt="Profile Picture" />
                                        </td>
                                        <td class="largerText">
                                            @Html.Label(item.user.LastName + ", " + item.memberSurvey.prefName)
                                        </td>
                                        <td>
                                            <button id="btnApprove" memberid="@item.user.MemberID" name="button" value="approve"
                                        class="ui-button ui-button-text-only ui-widget ui-state-default ui-corner-all">
                                                <span class="ui-button-text">Approve</span></button>
                                            <button id="btnDeny" memberid="@item.user.MemberID" name="button" value="deny"
                                        class="ui-button ui-button-text-only ui-widget ui-state-default ui-corner-all">
                                                <span class="ui-button-text">Deny</span>
                                            </button>
                                        </td>
                                    </tr>
                                }
                            </table>
                        }
                    </div>
                </div>
            }
        </td>
        <td>
            <!--  start Information & Features -->
            <div id="related-activities">
                <!--  start related-act-top -->
                <div id="related-act-top">
                    <img src="../../Content/admin/images/forms/header_related_act.gif" width="271" height="43"
                        alt="" />
                </div>
                <!-- end related-act-top -->
                <!--  start related-act-bottom -->
                <div id="related-act-bottom">
                    <!--  start related-act-inner -->
                    <div id="related-act-inner">
                        <div class="left">
                            <img src="../../Content/admin/images/forms/icon_edit.gif" width="21" height="21"
                                alt="" /></div>
                        <div class="right">
                            <h5>
                                Organization Options</h5>
                            <ul class="greyarrow">
                                @if (Model.org.ReportID == "Elders Quorum")
                                {
									if (!bool.Parse(Session["IsBishopric"] as string))
									{ 
									<li>@Html.ActionLink("Home Teaching", "Teaching", "Organization")</li>
									}
                                    <li>@Html.ActionLink("Quorum Membership", "Membership", "Organization")</li>
                                }
                                else
                                {
									if (!bool.Parse(Session["IsBishopric"] as string))
									{ 
                                    <li>@Html.ActionLink("Visiting Teaching", "Teaching", "Organization")</li>
									}
                                    <li>@Html.ActionLink("Relief Society Membership", "Membership", "Organization")</li>
                                }
                            </ul>
                        </div>
                        <div class="clear">
                        </div>
                        @if (User.IsInRole("Elders Quorum") || User.IsInRole("Relief Society") || User.IsInRole("Bishopric") || User.IsInRole("District Leader"))
                        {                   
                            <div class="lines-dotted-short">
                            </div>
                            <div class="left">
                                <img src="../../Content/admin/images/forms/icon_edit.gif" width="21" height="21"
                                    alt="" /></div>
                            <div class="right">
                                <h5>
                                    Leadership Options</h5>
                                <ul class="greyarrow">
                                    @if (User.IsInRole("Elders Quorum") || User.IsInRole("Relief Society") || User.IsInRole("Bishopric"))
                                    {
                                        if (Model.org.ReportID == "Elders Quorum")
                                        {
                                        <li>@Html.ActionLink("Manage Home Teaching", "ManageTeaching", "Organization")</li>
                                        <li>@Html.ActionLink("Report Home Teaching", "ReportTeaching", "Organization")</li>
                                        }
                                        else
                                        {
                                        <li>@Html.ActionLink("Manage Visiting Teaching", "ManageTeaching", "Organization")</li>
                                        <li>@Html.ActionLink("Report Visiting Teaching", "ReportTeaching", "Organization")</li>
                                        }
                                        <li>@Html.ActionLink("Send Notification", "SendNotification", "Group")</li>
                                        <li>@Html.ActionLink("Reports", "Reports", "Organization")</li>
                                    }
                                    else
                                    {
                                        if (Model.org.ReportID == "Elders Quorum")
                                        {
                                        <li>@Html.ActionLink("Report Home Teaching", "ReportTeaching", "Organization")</li>
                                        }
                                        else
                                        {
                                        <li>@Html.ActionLink("Report Visiting Teaching", "ReportTeaching", "Organization")</li>
                                        }
                                    }
                                </ul>
                            </div>
                            <div class="clear">
                            </div> 
                        }
                    </div>
                    <!-- end related-act-inner -->
                    <div class="clear">
                    </div>
                </div>
                <!-- end related-act-bottom -->
            </div>
            <!-- end Information & Features -->
        </td>
    </tr>
    <tr>
        <td>
            <img src="../../Content/admin/images/shared/blank.gif" width="695" height="1" alt="blank" />
        </td>
        <td>
        </td>
    </tr>
</table>
<div style="clear: both;">
</div>
<!--Dialog for Managing Quorum membership-->
@if (User.IsInRole("Elders Quorum") || User.IsInRole("Relief Society") || User.IsInRole("Bishopric"))
{     
    <div id="dialog" title="Manage Membership">
        <center id="loading">
            <img src="../../Content/images/loading.gif" style="width: 100px" /></center>
        <div id="membershipList">
        </div>
    </div>
}
<script type="text/javascript">
    //Membership Approval
    $("[id=btnApprove]").click(function () {

        var memberID = $(this).attr("memberID");
        SendApprovalRequest('approve', memberID);
    });
    $("[id=btnDeny]").click(function () {

        var memberID = $(this).attr("memberID");
        SendApprovalRequest('deny', memberID);
    });

    function SendApprovalRequest(button, memberID) {
        $.ajax({
            url: '/Organization/ApproveNewMembership',
            data: { button: button, Memberid: memberID },
            success: function (data) {
                $('#' + memberID).hide();
            },
            error: function (error) {
                alert("An error has occurred: " + error);
            }

        });
    }

    $(document).ready(function () {
        // Tabs
        var $tabs = $('#tabs').tabs(); // first tab selected
    });
</script>
<script src="../../Scripts/OrganizationMembership.js" type="text/javascript"></script>
@section MenuScript{
    <script type="text/javascript">
        MenuSelect("Organization", "orgProfile");
    </script>
}

MySinglesWard/Views/Organization/ManageMembership.cshtml
@model MSW.Models.MSWOrganizationModel
<span class="toggle" id="addressSort"><span class="toggleText">Sort By Address</span><img
    src="../../Content/images/refresh.png" style="width: 24px"></span> <span class="toggle"
        style="display: none" id="nameSort"><span class="toggleText">Sort By Name</span><img
            src="../../Content/images/refresh.png" style="width: 24px"></span>
            
	<script src="../../Scripts/jquery.blockUI.js" type="text/javascript"></script>
@using (Html.BeginForm("ManageMembership", "Organization", FormMethod.Post, new { @id = "AddMembershipList" }))
{
    <table class="orgMembership tablesorter" id="MemberTable">
        <thead>
            <tr>
                <th>
                </th>
                <th>
                    <strong>Member</strong>
                </th>
                <th>
                    <strong>Address</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var member in Model.MembersNotInOrganization)
            {
                <tr>
                    <td>@Html.CheckBox(member.user.MemberID.ToString())
                    </td>
                    <td>@member.user.LastName, @member.memberSurvey.prefName
                    </td>
                    <td>@member.memberSurvey.residence
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<script src="../../Scripts/jquery.tablesorter.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#MemberTable").tablesorter();

        $('#addressSort').click(function () {
            $(this).hide();
            $('#nameSort').show();

            var sorting = [[2, 0], [1, 0]];
            $("#MemberTable").trigger("sorton", [sorting]);
        });

        $('#nameSort').click(function () {
            $(this).hide();
            $('#addressSort').show();

            var sorting = [[1, 0]];
            $("#MemberTable").trigger("sorton", [sorting]);
        });
    });
</script>

MySinglesWard/Views/Organization/OrganizationPending.cshtml
@{
    Page.Title = "Organization Pending";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
    Page.Header = "My Organization";
}
<p>
    You are currently being considered for an organization. Please contact your organization
    leader to get approved into the organization.</p>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

MySinglesWard/Views/Organization/WithoutCallings.cshtml
@model IEnumerable<System.Web.UI.WebControls.ListItem>
@{
    Layout = null;
}
<table>
    @if (Model.Count() > 0)
    {
        foreach (var member in Model)
        { 
        <tr>
            <td>
                @Html.ActionLink(member.Text, "GetMember", "Home", new { memberID = member.Value }, new { @target = "_blank" })
            </td>
        </tr>
        }
    }
    else
    { 
        <tr>
            <td>
                Every member has a calling.
            </td>
        </tr>
    }
</table>